const EXPO_PUBLIC_SUPABASE_URL = process.env.EXPO_PUBLIC_SUPABASE_URL || "";
const EXPO_PUBLIC_SUPABASE_ANON_KEY = process.env.EXPO_PUBLIC_SUPABASE_KEY || "";
const API_URL = process.env.API_URL || "https://fakestoreapi.com";
const BACKEND_API_URL = process.env.EXPO_PUBLIC_BACKEND_API_URL || "http://localhost:8000";
const EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY = process.env.EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY || "";

export {
    API_URL,
    EXPO_PUBLIC_SUPABASE_ANON_KEY,
    EXPO_PUBLIC_SUPABASE_URL,
    BACKEND_API_URL,
    EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY
};